---
- name: Disable wireguard VPN
  command: wg-quick down "~/.wireguard/wg0.conf"

- name: Manage droplet
  digital_ocean_droplet:
    state: absent
    oauth_token: "{{ api_token }}"
    name: "wg-vpn-{{ region }}"
    unique_name: yes
