---
- name: Insert ssh key
  digital_ocean:
    command: ssh
    name: my_ssh_key
    ssh_pub_key: "{{ public_key }}"
    api_token: "{{ api_token }}"
  register: ssh_key

- name: Manage droplet
  digital_ocean:
    state: present
    command: droplet
    name: temp-2
    ssh_key_ids: "{{ ssh_key.ssh_key.id }}"
    api_token: "{{ api_token }}"
    size_id: s-1vcpu-1gb
    region_id: "{{ region }}"
    image_id: ubuntu-16-04-x64
    unique_name: yes
  register: do

- debug:
    msg: "Droplet created. IP is {{ do.droplet.ip_address }}"

- name: Add node to inventory
  add_host:
    name: "{{ do.droplet.ip_address }}"
    groups: main
  when: do.droplet is defined
