---
- name: Insert ssh key
  digital_ocean_sshkey:
    name: laptop
    ssh_pub_key: "{{ public_key }}"
    oauth_token: "{{ api_token }}"
    state: present
  register: ssh_key

- name: Manage droplet
  digital_ocean_droplet:
    state: present
    name: "wg-vpn-{{ region }}"
    ssh_keys: "{{ ssh_key.data.ssh_key.id }}"
    oauth_token: "{{ api_token }}"
    size: 1gb
    region: "{{ region }}"
    image_id: ubuntu-20-04-x64
    unique_name: yes
  register: do

- debug:
    msg: "Droplet created. IP is {{ do.data.ip_address }}"

- name: Add node to inventory
  add_host:
    name: "{{ do.data.ip_address }}"
    groups: main
  when: do.data is defined
