---
- name: Default task create if not defined
  set_fact:
    task: "create"
  when: task is not defined

- include_tasks: create.yml
  when: task == "create"

- include_tasks: cleanup.yml
  when: task == "cleanup"
